$axure.loadCurrentPage({
  "url":"魅力榜.html",
  "generationDate":new Date(1451359024361.01),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"464e5aa0c8c349ed8f175608b0d6bc1f",
    "type":"Axure:Page",
    "name":"魅力榜",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9d3c98701d594175bee49b3c3aa0d89b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'PingFang SC'",
            "location":{
              "x":180,
              "y":26},
            "size":{
              "width":489,
              "height":594}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6f79ca530da4ad88eca7c7a3b435181",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'PingFang SC'",
                "location":{
                  "x":180,
                  "y":26},
                "size":{
                  "width":489,
                  "height":594}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5de21bf1f4dc4e388476cf27f221ebba",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":590},
            "size":{
              "width":320,
              "height":570}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9bf5199be23446ab5cdd97194c773b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":590},
                "size":{
                  "width":320,
                  "height":570}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/魅力榜/u2.png"}},
{
          "id":"af0cb3942a79444ebe87bec148aebfd6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":610},
            "size":{
              "width":294,
              "height":505}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"529b7d0a3e2d4de7aa3935dd66e29377",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":610},
                "size":{
                  "width":294,
                  "height":505}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/魅力榜/u4.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "9d3c98701d594175bee49b3c3aa0d89b":{
      "scriptId":"u0"},
    "d6f79ca530da4ad88eca7c7a3b435181":{
      "scriptId":"u1"},
    "5de21bf1f4dc4e388476cf27f221ebba":{
      "scriptId":"u2"},
    "a9bf5199be23446ab5cdd97194c773b3":{
      "scriptId":"u3"},
    "af0cb3942a79444ebe87bec148aebfd6":{
      "scriptId":"u4"},
    "529b7d0a3e2d4de7aa3935dd66e29377":{
      "scriptId":"u5"}}});