$axure.loadCurrentPage({
  "url":"赠送礼物的入口和人物选择.html",
  "generationDate":new Date(1451359024185),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8df78ff9f6c34875bab4cb167e8c238a",
    "type":"Axure:Page",
    "name":"赠送礼物的入口和人物选择",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"64417b32dfba47d78879eca7767ec387",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'PingFang SC'",
            "location":{
              "x":60,
              "y":50},
            "size":{
              "width":401,
              "height":221}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4eafa72ce7a64d41867d8a0c5b3accf4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'PingFang SC'",
                "location":{
                  "x":60,
                  "y":50},
                "size":{
                  "width":401,
                  "height":221}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d2f5546b531c403e80be01ded2204142",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1230,
              "y":310},
            "size":{
              "width":300,
              "height":529}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0780549c0a642dba74412335bb429c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1230,
                  "y":310},
                "size":{
                  "width":300,
                  "height":529}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/赠送礼物的入口和人物选择/u2.png"}},
{
          "id":"3b94f0c9e10a4efcb708e9f6eb7913c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'PingFang SC'",
            "location":{
              "x":714,
              "y":50},
            "size":{
              "width":1146,
              "height":226}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d32f62b29d4d41aca51ecdfa6ddc2c20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'PingFang SC'",
                "location":{
                  "x":714,
                  "y":50},
                "size":{
                  "width":1146,
                  "height":226}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f80e35ced3934bdca29bc4e74e76d1c9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":714,
              "y":316},
            "size":{
              "width":299,
              "height":523}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9568eb88976b44c092429e863dcd1136",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":714,
                  "y":316},
                "size":{
                  "width":299,
                  "height":523}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/赠送礼物的入口和人物选择/u6.png"}},
{
          "id":"87ac64b8d17848b5916499cab86369d7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":317},
            "size":{
              "width":237,
              "height":262}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"569bc5436e6a472dba3e3745d46a62c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":317},
                "size":{
                  "width":237,
                  "height":262}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/赠送礼物的主流程-总述/u16.png"}},
{
          "id":"2d6e3abcb62f4911b62f7aaafd4a93f6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":318},
            "size":{
              "width":224,
              "height":261}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e0d43ee9f834107a4c0859049bf1a1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":318},
                "size":{
                  "width":224,
                  "height":261}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/赠送礼物的主流程-总述/u22.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "64417b32dfba47d78879eca7767ec387":{
      "scriptId":"u0"},
    "4eafa72ce7a64d41867d8a0c5b3accf4":{
      "scriptId":"u1"},
    "d2f5546b531c403e80be01ded2204142":{
      "scriptId":"u2"},
    "f0780549c0a642dba74412335bb429c4":{
      "scriptId":"u3"},
    "3b94f0c9e10a4efcb708e9f6eb7913c3":{
      "scriptId":"u4"},
    "d32f62b29d4d41aca51ecdfa6ddc2c20":{
      "scriptId":"u5"},
    "f80e35ced3934bdca29bc4e74e76d1c9":{
      "scriptId":"u6"},
    "9568eb88976b44c092429e863dcd1136":{
      "scriptId":"u7"},
    "87ac64b8d17848b5916499cab86369d7":{
      "scriptId":"u8"},
    "569bc5436e6a472dba3e3745d46a62c9":{
      "scriptId":"u9"},
    "2d6e3abcb62f4911b62f7aaafd4a93f6":{
      "scriptId":"u10"},
    "1e0d43ee9f834107a4c0859049bf1a1e":{
      "scriptId":"u11"}}});