$axure.loadCurrentPage({
  "url":"关注直播与召唤粉丝.html",
  "generationDate":new Date(1451359024464.01),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a650929855b84bedb39127d7862927c5",
    "type":"Axure:Page",
    "name":"关注直播与召唤粉丝",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"40c49a92a5d24d6f8808df09dbb38e5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":754,
              "y":282},
            "size":{
              "width":290,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6584d90fc92402cbec94cb828861271",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":754,
                  "y":282},
                "size":{
                  "width":290,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e79e3262209e48d3988ebde248dd27b2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":742,
              "y":209},
            "size":{
              "width":282,
              "height":502}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df27e0830aa34ebb8c74e6b0c86ab8e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":742,
                  "y":209},
                "size":{
                  "width":282,
                  "height":502}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注直播与召唤粉丝/u2.jpg"}},
{
          "id":"c4b6c25bc2a747bd96201ff2883f356d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":874,
              "y":542},
            "size":{
              "width":74,
              "height":74}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3315d13795014d7b94c74540d3489271",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":874,
                  "y":542},
                "size":{
                  "width":74,
                  "height":74}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/房间部分优化/u0.png"}},
{
          "id":"4bf9f39947894371aa27246126bda64f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":856,
              "y":653},
            "size":{
              "width":32,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7f7d5c1ee3a4f839da93a8be18afdbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":856,
                  "y":653},
                "size":{
                  "width":32,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"def3958d36fa497f8c0e394dff70cf26",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":874,
              "y":626},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4b827b1ce444cf6bc5978ac4b1741ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":874,
                  "y":626},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de65f95f57c142e2b2bbe128e1ec2337",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":804,
              "y":142},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebbd5787035a476aab9cd5a411d7fab3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":804,
                  "y":142},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"213ec76009484845b4a168af2401b24e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'PingFang SC'",
            "location":{
              "x":258,
              "y":792},
            "size":{
              "width":856,
              "height":1058}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12db8157345a408a9e09f1462a27f53f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'PingFang SC'",
                "location":{
                  "x":258,
                  "y":792},
                "size":{
                  "width":856,
                  "height":1058}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01aab1393b11491b97de8efb31c27bb2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":235,
              "y":208},
            "size":{
              "width":289,
              "height":513}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ff7ec3f5b1842b68d9189a31b9f9db7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":235,
                  "y":208},
                "size":{
                  "width":289,
                  "height":513}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关注直播与召唤粉丝/u14.png"}},
{
          "id":"3a310467147445878a7eb8fb5f86c997",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":244,
              "y":132},
            "size":{
              "width":193,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94a9e6638fdd48a293a185ceb9d18da3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":244,
                  "y":132},
                "size":{
                  "width":193,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "40c49a92a5d24d6f8808df09dbb38e5c":{
      "scriptId":"u0"},
    "a6584d90fc92402cbec94cb828861271":{
      "scriptId":"u1"},
    "e79e3262209e48d3988ebde248dd27b2":{
      "scriptId":"u2"},
    "df27e0830aa34ebb8c74e6b0c86ab8e6":{
      "scriptId":"u3"},
    "c4b6c25bc2a747bd96201ff2883f356d":{
      "scriptId":"u4"},
    "3315d13795014d7b94c74540d3489271":{
      "scriptId":"u5"},
    "4bf9f39947894371aa27246126bda64f":{
      "scriptId":"u6"},
    "f7f7d5c1ee3a4f839da93a8be18afdbd":{
      "scriptId":"u7"},
    "def3958d36fa497f8c0e394dff70cf26":{
      "scriptId":"u8"},
    "f4b827b1ce444cf6bc5978ac4b1741ad":{
      "scriptId":"u9"},
    "de65f95f57c142e2b2bbe128e1ec2337":{
      "scriptId":"u10"},
    "ebbd5787035a476aab9cd5a411d7fab3":{
      "scriptId":"u11"},
    "213ec76009484845b4a168af2401b24e":{
      "scriptId":"u12"},
    "12db8157345a408a9e09f1462a27f53f":{
      "scriptId":"u13"},
    "01aab1393b11491b97de8efb31c27bb2":{
      "scriptId":"u14"},
    "3ff7ec3f5b1842b68d9189a31b9f9db7":{
      "scriptId":"u15"},
    "3a310467147445878a7eb8fb5f86c997":{
      "scriptId":"u16"},
    "94a9e6638fdd48a293a185ceb9d18da3":{
      "scriptId":"u17"}}});