$axure.loadCurrentPage({
  "url":"个人资料增加礼物展示和魅力值.html",
  "generationDate":new Date(1451359024512.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4be0024bad1d49deb556ba10c8d5320c",
    "type":"Axure:Page",
    "name":"个人资料增加礼物展示和魅力值",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0ee0c6134f254cbea4377be3e0fb9c72",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":433,
              "y":11},
            "size":{
              "width":707,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f066358cb9e42b79177a9ba15faa3f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":433,
                  "y":11},
                "size":{
                  "width":707,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4933209328ff498e95381b4d277864ec",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":10},
            "size":{
              "width":294,
              "height":822}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efc197281e2143128bd37d14ab097130",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":10},
                "size":{
                  "width":294,
                  "height":822}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人资料增加礼物展示和魅力值/u2.png"}},
{
          "id":"2afe1c92647440ec964a8a640db5f14e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":260},
            "size":{
              "width":674,
              "height":93}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a2a34f1f1ff47719447b721d9251714",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":260},
                "size":{
                  "width":674,
                  "height":93}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7ceaced3de640318ca6b588f16e100f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":458,
              "y":438},
            "size":{
              "width":495,
              "height":1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75455312249347d4bd9d91373d8e82f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":458,
                  "y":438},
                "size":{
                  "width":495,
                  "height":1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00156e5b74dd4f4ebf04e4be2e4f760b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":586},
            "size":{
              "width":707,
              "height":1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a63e011e4bb4439d845eb61008e77d94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":586},
                "size":{
                  "width":707,
                  "height":1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "0ee0c6134f254cbea4377be3e0fb9c72":{
      "scriptId":"u0"},
    "4f066358cb9e42b79177a9ba15faa3f7":{
      "scriptId":"u1"},
    "4933209328ff498e95381b4d277864ec":{
      "scriptId":"u2"},
    "efc197281e2143128bd37d14ab097130":{
      "scriptId":"u3"},
    "2afe1c92647440ec964a8a640db5f14e":{
      "scriptId":"u4"},
    "7a2a34f1f1ff47719447b721d9251714":{
      "scriptId":"u5"},
    "a7ceaced3de640318ca6b588f16e100f":{
      "scriptId":"u6"},
    "75455312249347d4bd9d91373d8e82f8":{
      "scriptId":"u7"},
    "00156e5b74dd4f4ebf04e4be2e4f760b":{
      "scriptId":"u8"},
    "a63e011e4bb4439d845eb61008e77d94":{
      "scriptId":"u9"}}});