$axure.loadCurrentPage({
  "url":"房间列表新增附近的人列表.html",
  "generationDate":new Date(1451359024422.01),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f1fcf822d77946dba865633b2d8318e8",
    "type":"Axure:Page",
    "name":"房间列表新增附近的人列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ab427d03c3f549b7b76956b6e987ca90",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'PingFang SC'",
            "fontSize":"20px",
            "location":{
              "x":760,
              "y":928},
            "size":{
              "width":626,
              "height":192}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bab6f9f1f3ac417f9559158f3d8d9aed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'PingFang SC'",
                "fontSize":"20px",
                "location":{
                  "x":760,
                  "y":928},
                "size":{
                  "width":626,
                  "height":192}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a9b379aeb214ad39ea81f5bc891b0c4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":146,
              "y":151},
            "size":{
              "width":384,
              "height":679}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"834107693226458aa65008c89d463208",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":146,
                  "y":151},
                "size":{
                  "width":384,
                  "height":679}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/房间列表新增附近的人列表/u2.png"}},
{
          "id":"142fa15cc90f43b6a89ca6573edec944",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":145.5},
            "size":{
              "width":391,
              "height":690}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62f53f4b474c4fc2818262412df71943",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":740,
                  "y":145.5},
                "size":{
                  "width":391,
                  "height":690}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/房间列表新增附近的人列表/u4.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "ab427d03c3f549b7b76956b6e987ca90":{
      "scriptId":"u0"},
    "bab6f9f1f3ac417f9559158f3d8d9aed":{
      "scriptId":"u1"},
    "5a9b379aeb214ad39ea81f5bc891b0c4":{
      "scriptId":"u2"},
    "834107693226458aa65008c89d463208":{
      "scriptId":"u3"},
    "142fa15cc90f43b6a89ca6573edec944":{
      "scriptId":"u4"},
    "62f53f4b474c4fc2818262412df71943":{
      "scriptId":"u5"}}});