$axure.loadCurrentPage({
  "url":"房间内部进出关系优化.html",
  "generationDate":new Date(1451359024408.01),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0e676a4253224a0e93d75d233a7fe780",
    "type":"Axure:Page",
    "name":"房间内部进出关系优化",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e9efd8e7ba7b41faa9924ef91685bdd3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":136,
              "y":55},
            "size":{
              "width":274,
              "height":459}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8aaae09f1774d02a4bf09ac7e49275c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":136,
                  "y":55},
                "size":{
                  "width":274,
                  "height":459}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/房间内部进出关系优化/u0.jpg"}},
{
          "id":"41e4745e9d034df09847828f98629efa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'PingFang SC'",
            "fontSize":"20px",
            "location":{
              "x":144,
              "y":570},
            "size":{
              "width":416,
              "height":192}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cf682142d2a4337ba4266a7ae531e3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'PingFang SC'",
                "fontSize":"20px",
                "location":{
                  "x":144,
                  "y":570},
                "size":{
                  "width":416,
                  "height":192}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"489a1bed73384d0fa6ecfc68a904b9b6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":521,
              "y":55},
            "size":{
              "width":259,
              "height":465}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27be2e74b3054e3b8572e68c9adb3657",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":521,
                  "y":55},
                "size":{
                  "width":259,
                  "height":465}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/房间内部进出关系优化/u4.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "e9efd8e7ba7b41faa9924ef91685bdd3":{
      "scriptId":"u0"},
    "e8aaae09f1774d02a4bf09ac7e49275c":{
      "scriptId":"u1"},
    "41e4745e9d034df09847828f98629efa":{
      "scriptId":"u2"},
    "9cf682142d2a4337ba4266a7ae531e3a":{
      "scriptId":"u3"},
    "489a1bed73384d0fa6ecfc68a904b9b6":{
      "scriptId":"u4"},
    "27be2e74b3054e3b8572e68c9adb3657":{
      "scriptId":"u5"}}});